# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rservice.proto\"\x1e\n\nVarRequest\x12\x10\n\x08varValue\x18\x01 \x01(\t\"c\n\x10OperationRequest\x12.\n\toperation\x18\x01 \x01(\x0e\x32\x1b.OperationRequest.Operation\"\x1f\n\tOperation\x12\x07\n\x03SUM\x10\x00\x12\t\n\x05MULTY\x10\x01\"!\n\x0fOperationResult\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x1c\n\x0bVarResponse\x12\r\n\x05reply\x18\x01 \x01(\t2m\n\x13\x43omunicationService\x12$\n\x07SendVar\x12\x0b.VarRequest\x1a\x0c.VarResponse\x12\x30\n\tOperation\x12\x11.OperationRequest\x1a\x10.OperationResultb\x06proto3')
)



_OPERATIONREQUEST_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='OperationRequest.Operation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUM', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTY', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=117,
  serialized_end=148,
)
_sym_db.RegisterEnumDescriptor(_OPERATIONREQUEST_OPERATION)


_VARREQUEST = _descriptor.Descriptor(
  name='VarRequest',
  full_name='VarRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='varValue', full_name='VarRequest.varValue', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=47,
)


_OPERATIONREQUEST = _descriptor.Descriptor(
  name='OperationRequest',
  full_name='OperationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='OperationRequest.operation', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OPERATIONREQUEST_OPERATION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=148,
)


_OPERATIONRESULT = _descriptor.Descriptor(
  name='OperationResult',
  full_name='OperationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='OperationResult.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=183,
)


_VARRESPONSE = _descriptor.Descriptor(
  name='VarResponse',
  full_name='VarResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='VarResponse.reply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=213,
)

_OPERATIONREQUEST.fields_by_name['operation'].enum_type = _OPERATIONREQUEST_OPERATION
_OPERATIONREQUEST_OPERATION.containing_type = _OPERATIONREQUEST
DESCRIPTOR.message_types_by_name['VarRequest'] = _VARREQUEST
DESCRIPTOR.message_types_by_name['OperationRequest'] = _OPERATIONREQUEST
DESCRIPTOR.message_types_by_name['OperationResult'] = _OPERATIONRESULT
DESCRIPTOR.message_types_by_name['VarResponse'] = _VARRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VarRequest = _reflection.GeneratedProtocolMessageType('VarRequest', (_message.Message,), {
  'DESCRIPTOR' : _VARREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:VarRequest)
  })
_sym_db.RegisterMessage(VarRequest)

OperationRequest = _reflection.GeneratedProtocolMessageType('OperationRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:OperationRequest)
  })
_sym_db.RegisterMessage(OperationRequest)

OperationResult = _reflection.GeneratedProtocolMessageType('OperationResult', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONRESULT,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:OperationResult)
  })
_sym_db.RegisterMessage(OperationResult)

VarResponse = _reflection.GeneratedProtocolMessageType('VarResponse', (_message.Message,), {
  'DESCRIPTOR' : _VARRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:VarResponse)
  })
_sym_db.RegisterMessage(VarResponse)



_COMUNICATIONSERVICE = _descriptor.ServiceDescriptor(
  name='ComunicationService',
  full_name='ComunicationService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=215,
  serialized_end=324,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendVar',
    full_name='ComunicationService.SendVar',
    index=0,
    containing_service=None,
    input_type=_VARREQUEST,
    output_type=_VARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Operation',
    full_name='ComunicationService.Operation',
    index=1,
    containing_service=None,
    input_type=_OPERATIONREQUEST,
    output_type=_OPERATIONRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMUNICATIONSERVICE)

DESCRIPTOR.services_by_name['ComunicationService'] = _COMUNICATIONSERVICE

# @@protoc_insertion_point(module_scope)
